### ISSUE TITLE
Header comments get removed

### ISSUE THREAD

**Issue by hoijui** [TomPridham/cargo-funnel#10]
In the top of my Cargo.toml, I have REUSE/SPDX license header info in two comments,
which get removed by a run of `cargo funnel`.

I understand you made this tool mostly for yourself,
so it is fine if you do not have time/do not plan to fix such stuff that does not concern you.

example:

```toml
# SPDX-FileCopyrightText: 2021 Joe Doe <joe.doe@mail.com>
#
# SPDX-License-Identifier: Unlicense

[package]
name = "myproj"
version = "0.8.0"
edition = "2021"
description = """
    A tiny CLI tool that ...
    """
repository = "https://github.com/joe/myproj"
keywords = ["cli", "ci"]
categories = ["command-line-utilities", "text-processing"]
license = "GPL-3.0-or-later"
authors = ["Joe Doe <joe.doe@mail.com>"]
publish = false
```
